### Understand the Dataset

In [1]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [2]:
# Loading the data 
df = pd.read_csv(r"D:\NTI-ML\nti-projects\employee-attrition-analysis\data\raw\employee_attrition_course.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,RecordID,ManagerNotes
0,41.0,Yes,Travel_Rarely,1102,sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,NaN,19479,8,Y,Yes,11,3,1,80,0,8.0,0,1,6.0,4,0,5,100001,NaN
1,49.0,No,Travel_Frequently,279,Research and Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,NaN,24907,1,Y,No,23,4,4,80,1,10.0,3,3,10.0,7,1,7,100002,NaN
2,37.0,Yes,Travel_Rarely,1373,Research and Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090.0,2396,6,Y,Yes,15,3,2,80,0,7.0,3,3,0.0,0,0,0,100003,Needs Improvement
3,33.0,No,Travel_Frequently,1392,Research and Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909.0,23159,1,Y,Yes,11,3,3,80,0,8.0,3,3,NaN,7,3,0,100004,Average
4,27.0,No,Travel_Rarely,591,Research and Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468.0,16632,9,Y,No,12,3,4,80,1,6.0,3,3,2.0,2,2,2,100005,NaN

In [4]:
# Show the shape 
print("(Rows , Columns)",df.shape)

(Rows , Columns) (1495, 37)

In [5]:
# Overviow
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1451 non-null   float64
 1   Attrition                 1495 non-null   object
 2   BusinessTravel            1495 non-null   object
 3   DailyRate                 1495 non-null   int64
 4   Department                1495 non-null   object
 5   DistanceFromHome          1495 non-null   int64
 6   Education                 1495 non-null   int64
 7   EducationField            1466 non-null   object
 8   EmployeeCount             1495 non-null   int64
 9   EmployeeNumber            1495 non-null   int64
 10  EnvironmentSatisfaction   1495 non-null   int64
 11  Gender                    1495 non-null   object
 12  HourlyRate                1495 non-null   int64
 13  JobInvolvement            1495 non-null   int64
 14  JobLevel                  1495 non-null   int64
 15  JobRole                   1480 non-null   object
 16  JobSatisfaction           1495 non-null   int64
 17  MaritalStatus             1495 non-null   object
 18  MonthlyIncome             1375 non-null   float64
 19  MonthlyRate               1495 non-null   int64
 20  NumCompaniesWorked        1495 non-null   int64
 21  Over18                    1495 non-null   object
 22  OverTime                  1495 non-null   object
 23  PercentSalaryHike         1495 non-null   int64
 24  PerformanceRating         1495 non-null   int64
 25  RelationshipSatisfaction  1495 non-null   int64
 26  StandardHours             1495 non-null   int64
 27  StockOptionLevel          1495 non-null   int64
 28  TotalWorkingYears         1434 non-null   float64
 29  TrainingTimesLastYear     1495 non-null   int64
 30  WorkLifeBalance           1495 non-null   int64
 31  YearsAtCompany            1420 non-null   float64
 32  YearsInCurrentRole        1495 non-null   int64
 33  YearsSinceLastPromotion   1495 non-null   int64
 34  YearsWithCurrManager      1495 non-null   int64
 35  RecordID                  1495 non-null   int64
 36  ManagerNotes              598 non-null    object
dtypes: float64(4), int64(23), object(10)
memory usage: 432.3+ KB

In [7]:
# Statistical description of numerical columns
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,RecordID
count,1451.000000,1495.000000,1495.000000,1495.000000,1495.0,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1375.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.000000,1495.0,1495.000000,1434.000000,1495.000000,1495.000000,1420.000000,1495.000000,1495.000000,1495.000000,1495.000000
mean,36.973122,800.762542,9.442140,2.915050,1.0,1027.762542,2.730435,65.882943,2.728428,2.063545,2.725084,7717.508364,14261.773244,2.691639,15.202676,3.154515,2.711037,80.0,0.790635,11.273361,2.800000,2.761873,7.065493,4.230100,2.199331,4.125753,100739.142475
std,9.229636,403.789611,9.590084,1.026494,0.0,601.875560,1.091640,20.350715,0.709348,1.110062,1.101906,21151.885011,7108.869434,2.494015,3.658222,0.361563,1.081414,0.0,0.848445,7.833083,1.286112,0.707214,6.200031,3.616196,3.226667,3.563383,424.837215
min,16.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,100001.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,493.500000,2.000000,48.000000,2.000000,1.000000,2.000000,2935.500000,8012.500000,1.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000,100371.000000
50%,36.000000,798.000000,7.000000,3.000000,1.0,1025.000000,3.000000,66.000000,3.000000,2.000000,3.000000,4941.000000,14120.000000,2.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000,100740.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1556.500000,4.000000,84.000000,3.000000,3.000000,4.000000,8468.500000,20435.000000,4.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000,101107.500000
max,78.000000,1499.000000,150.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,500000.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000,101470.000000

In [8]:
# Statistical description of categorical columns
df.describe(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime,ManagerNotes
count,1495,1495,1495,1466,1495,1480,1495,1495,1495,598
unique,2,7,3,6,4,12,3,1,2,3
top,No,Travel_Rarely,Research and Development,Life Sciences,Male,Sales Executive,Married,Y,No,Good
freq,1256,1051,973,605,878,321,690,1495,1070,211

Business Meaning: Quick Notes on Key Columns

- **Attrition:** Target Variable (Yes = Left / No = Still Employed).

- **Overtime, Monthly Income, Job Satisfaction, Department:** Key candidates influencing the decision.

- **Employee Count, Standard Hours, Over 18:** Columns that appear to have fixed values ​​(we will verify these in the quality assessment).

- **RecordID / EmployeeNumber:** ID columns, not analytical